name: Deploy to vercel

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      
      - name: Install vercel
        id: install-vercel
        run: |
          npm install --global vercel@latest

      - name: Pull vercel config
        id: pull-vercel-config
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build app
        id: build-app
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy app
        id: deploy-app
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}