name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  AWS_S3_BUCKET_STATIC: 'my-upload-widget-web-static'
  AWS_S3_BUCKET_CDN: 'my-upload-widget-web-cdn'
  SOURCE_DIST: './dist'

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to S3 static
        id: sync-files-to-s3-static
        run: |
          aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_STATIC }}/ --delete

      - name: Sync files to S3 CDN
        id: sync-files-to-s3-cdn
        run: |
          aws s3 sync ${{ env.SOURCE_DIST }} s3://${{ env.AWS_S3_BUCKET_CDN }}/ --delete